name: Generate and Deploy Thumbnails

on:
  push:
    paths:
      - '**/*.jpg'
      - '**/*.jpeg'
      - '**/*.png'
      - '**/*.gif'
      - '**/*.webp'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repo (sumaila-img)
        uses: actions/checkout@v4
        with:
          repository: duncanburnside/sumaila-img # The repo with original images
          path: source_repo

      - name: Checkout Target Repo (sumaila-img-thumbs)
        uses: actions/checkout@v4
        with:
          repository: duncanburnside/sumaila-img-thumbs # The repo for thumbnails
          token: ${{ secrets.THUMBS_GEN }}
          path: target_repo

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Sharp CLI
        run: npm install -g sharp-cli

      - name: Generate Thumbnails
        run: |
          find source_repo -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.gif" -o -iname "*.webp" \) | while read img_path; do
            relative_path="${img_path#source_repo/}"
            target_dir="target_repo/$(dirname "$relative_path")"
            target_filename="$(basename "$relative_path" | sed 's/\.[^.]*$/.jpeg/')"
            target_path="$target_dir/$target_filename"
            
            mkdir -p "$target_dir"
            
            # Only generate if the source is newer than the target, or if target doesn't exist
            if [ ! -f "$target_path" ] || [ "$(stat -c %Y "$img_path")" -gt "$(stat -c %Y "$target_path")" ]; then
              echo "Generating thumbnail for $relative_path"
              sharp --input "$img_path" --resize 300 300 --fit cover --position center --to-format jpeg --jpeg-quality 80 --output "$target_path"
            else
              echo "Thumbnail for $relative_path is up to date."
            fi
          done

      - name: Commit and Push Changes
        run: |
          cd target_repo
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Update thumbnails [$(date)]"
            git push
          else
            echo "No changes to commit."
          fi
